version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: toolbox_prod
    container_name: toolbox_prod_container
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - sqlite_volume:/app/db


    command: gunicorn --bind 0.0.0.0:8000 toolbox.wsgi:application

  nginx:
    image: nginx:latest
    container_name: nginx_prod_container
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  sqlite_volume:
