# Generated by Django 4.0 on 2023-07-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbcore', '0001_initial'),
    ]

    operations = [

        migrations.AlterField(
            model_name='category',
            name='category_url',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='next_page',
            field=models.SlugField(null=True),
        ),

        migrations.AlterField(
            model_name='onlineidea',
            name='category',
            field=models.ManyToManyField(to='tbcore.Category'),
        ),

        migrations.RenameField(
            model_name='category',
            old_name='short_description',
            new_name='description_1',
        ),
        migrations.AddField(
            model_name='category',
            name='description_2',
            field=models.TextField(null=True),
        ),
    ]
