# Generated by Django 4.0 on 2023-06-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbcore', '0002_alter_category_category_url_alter_category_next_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineidea',
            name='category',
            field=models.ManyToManyField(to='tbcore.Category'),
        ),
    ]
