# Generated by Django 4.0 on 2023-07-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbcore', '0003_alter_onlineidea_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='short_description',
            new_name='description_1',
        ),
        migrations.AddField(
            model_name='category',
            name='description_2',
            field=models.TextField(null=True),
        ),
    ]
