# Generated by Django 4.0.5 on 2022-08-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbcore', '0004_category_online_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='plancategoryonlineidea',
            constraint=models.UniqueConstraint(fields=('plan', 'category', 'idea'), name='plancategoryonlineidea_constraint'),
        ),
    ]
