# Generated by Django 4.0.5 on 2022-08-17 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbcore', '0004_category_online_idea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_note', models.TextField(null=True)),
                ('online_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_online_idea', to='tbcore.onlineidea')),
            ],
        ),
        migrations.AddField(
            model_name='plancategoryonlineidea',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_plan', to='tbcore.notes'),
        ),
    ]
