# Generated by Django 4.0.5 on 2022-09-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbcore', '0004_category_online_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancategoryonlineidea',
            name='notes',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
