# Generated by Django 4.0.5 on 2022-08-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbcore', '0005_alter_plan_plan_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('plan_name', 'user'), name='plan_constraint'),
        ),
    ]
